---
language: clojure
lein: 2.7.1
rvm: 2.4.1
sudo: false
cache: bundler
notifications:
  email: false

install: 'bundle install --without acceptance'

matrix:
  include:
    - jdk: openjdk8
      script: 'bundle exec rake test:integration'
    - jdk: oraclejdk8
      script: 'bundle exec rake test:integration'
    - jdk: openjdk8
      sudo: required
      services:
        - docker
      install: 'bundle install'
      script: "bundle exec rake 'test:acceptance[foss]'"
    - jdk: openjdk8
      sudo: required
      services:
        - docker
      install: 'bundle install'
      script: "bundle exec rake 'test:acceptance[pe]'"
