---
language: clojure
lein: 2.7.1
rvm: 2.4.1
sudo: false
cache: bundler
notifications:
  email: false

install: 'bundle install --without acceptance'

matrix:
  include:
    - jdk: openjdk8
      script: 'bundle exec rake test:integration'
      env: PUPPETSERVER_VERSION=5.1.5
    - jdk: oraclejdk8
      script: 'bundle exec rake test:integration'
      env: PUPPETSERVER_VERSION=5.1.5
    - jdk: openjdk8
      script: 'bundle exec rake test:integration'
      env: PUPPETSERVER_VERSION=5.2.0
    - jdk: openjdk8
      script: 'bundle exec rake test:integration'
      env: PUPPETSERVER_VERSION=5.3.0

    - jdk: openjdk8
      sudo: required
      services:
        - docker
      install: 'bundle install'
      env: PUPPETSERVER_VERSION=5.1.5
      script: "bundle exec rake 'test:acceptance[foss,centos7,5.1.5]'"
    - jdk: openjdk8
      sudo: required
      services:
        - docker
      install: 'bundle install'
      env: PUPPETSERVER_VERSION=5.2.0
      script: "bundle exec rake 'test:acceptance[foss,centos7,5.2.0]'"
    - jdk: openjdk8
      sudo: required
      services:
        - docker
      install: 'bundle install'
      env: PUPPETSERVER_VERSION=5.1.5
      script: "bundle exec rake 'test:acceptance[pe,centos7,2017.3.5]'"
