---
language: clojure
lein: 2.7.1
rvm: 2.4.4
sudo: false
cache: bundler
notifications:
  email: false

install: 'bundle install --without acceptance'
before_script: 'bundle exec rake puppetserver:install'

matrix:
  include:
    - jdk: openjdk8
      script: 'bundle exec rake test:integration'
      env: PUPPETSERVER_VERSION=2.6.1
    - jdk: openjdk8
      script: 'bundle exec rake test:integration'
      env: PUPPETSERVER_VERSION=5.1.6
    - jdk: oraclejdk8
      script: 'bundle exec rake test:integration'
      env: PUPPETSERVER_VERSION=5.1.6
    - jdk: openjdk8
      script: 'bundle exec rake test:integration'
      env: PUPPETSERVER_VERSION=5.2.0
    - jdk: openjdk8
      script: 'bundle exec rake test:integration'
      env: PUPPETSERVER_VERSION=5.3.6

    # Open Source acceptance tests
    - sudo: required
      services:
        - docker
      install: 'bundle install'
      # NOTE: 5.1.6 was not packaged for an Open Source release, so we test
      #       5.1.5 instead.
      env: PUPPETSERVER_VERSION=5.1.5
      script: "bundle exec rake 'test:acceptance[foss,centos7,5.1.5]'"
    - sudo: required
      services:
        - docker
      install: 'bundle install'
      env: PUPPETSERVER_VERSION=5.2.0
      script: "bundle exec rake 'test:acceptance[foss,centos7,5.2.0]'"
    - sudo: required
      services:
        - docker
      install: 'bundle install'
      env: PUPPETSERVER_VERSION=5.3.6
      script: "bundle exec rake 'test:acceptance[foss,centos7,5.3.5]'"

    # PE acceptance tests
    - sudo: required
      services:
        - docker
      install: 'bundle install'
      env: PUPPETSERVER_VERSION=5.1.6
      script: "bundle exec rake 'test:acceptance[pe,centos7,2017.3.10]'"
    - sudo: required
      services:
        - docker
      install: 'bundle install'
      env: PUPPETSERVER_VERSION=5.3.6
      script: "bundle exec rake 'test:acceptance[pe,centos7,2018.1.4]'"
